import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

export const frontendAbiDir = path.resolve(__dirname, "../../../src/lib/abi");
export const deploymentsDir = path.resolve(__dirname, "../../deployments");

const EXPORTED = ["WhipsLauncher"] as const;

export type DeploymentRecord = {
  network: string;
  chainId: number;
  deployer: string;
  ponsFactory: string;
  ponsForwarder: string;
  feeEscrow: string;
  launcher: string;
  catalogRoot: string;
  catalogSize: number;
  deployBlock: number;
  deployedAt: string;
  txHash: string | null;
};

/**
 * Writes each exported contract's ABI to ../src/lib/abi/<Name>.ts as an
 * `as const` array, so viem and wagmi infer argument and return types on
 * the front end.
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  fs.mkdirSync(frontendAbiDir, { recursive: true });
  for (const name of EXPORTED) {
    const artifact = await hre.artifacts.readArtifact(name);
    const file = path.join(frontendAbiDir, `${name}.ts`);
    const exportName = `${name[0].toLowerCase()}${name.slice(1)}Abi`;
    const header = "// Generated by contracts/scripts/lib/exportAbi.ts on every hardhat compile - do not edit.";
    const body = `${header}\nexport const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
    fs.writeFileSync(file, body);
  }
}
